"use client";

import { Block, SectionFrame } from "@/components/explore/SectionFrame";
import { int, pct } from "@/lib/format";

import { MetricsLoading, useMetrics } from "./shared";

export function LimitationsSection() {
  const state = useMetrics();
  if (state.status !== "ready") return <MetricsLoading state={state} />;
  const d = state.data;
  const m = d.metrics;
  const brand = m.model.by_merchant_kind.find((k) => k.kind === "brand");
  const at90 = m.model.coverage.find((c) => c.threshold === 0.9);

  return (
    <SectionFrame
      title="Limitations"
      stale={state.stale}
      method="transactions-limitations"
      methodLabel="Limitations"
      answer={
        <>
          Every number on this page comes from synthetic data. It shows the method working and failing in controlled conditions; it
          does not say how accurate the model would be on a real bank&apos;s statements.
        </>
      }
    >
      <Block title="What the numbers do and don't show">
        <ul className="tx-list">
          <li>
            <b>Synthetic, not real.</b> The {int(d.dataset.rows)} transactions were generated by code from {int(d.dataset.brands)} public
            brand names and invented local businesses. Real descriptors are messier, vary by bank and card network, and drift over time.
            Expect lower accuracy on real statements, by an amount this page cannot measure.
          </li>
          <li>
            <b>The generator and the model share assumptions.</b> The same person wrote the rules that produce descriptors and chose
            features to read them, so the features fit the data better than they would fit the world. The merchant split guards against
            memorizing names, not against this.
          </li>
          <li>
            <b>Unseen brands are the weak spot.</b>{" "}
            {brand ? <>On brands held out of training the model is right {pct(brand.accuracy, 0)} of the time.</> : null} A brand name
            carries no category words, so a new one is placed from its format and amount alone. A real system would add a merchant
            directory or look the name up.
          </li>
          <li>
            <b>Labels are simplified.</b> One category per transaction, from a fixed list of {int(d.dataset.categories)}. Real spending is
            split (a supercenter trip is groceries and household goods), and people disagree about categories. The generator labels some
            chain receipts either way on purpose, which sets an error floor.
          </li>
          <li>
            <b>Calibration is measured, not guaranteed.</b> Probabilities were calibrated on held-out merchants from the same generator.
            On data from another source the stated confidence would need checking again.
            {at90 && (
              <>
                {" "}
                The {pct(at90.accuracy, 1)} accuracy above 90% confidence holds for this test set only.
              </>
            )}
          </li>
          <li>
            <b>A bag of features.</b> Word order barely matters beyond two-word phrases, and the model cannot reason (it does not know that
            &quot;refund&quot; reverses a purchase). It is small and explainable by design; a larger model would likely do better on real
            data and be harder to explain.
          </li>
          <li>
            <b>No personal data, no storage.</b> Text you type is sent to the engine in the request, categorized, and not kept. Nothing
            here was trained on anyone&apos;s real transactions.
          </li>
        </ul>
      </Block>
      <Block title="Not a financial product">
        <p className="small" style={{ maxWidth: "var(--measure)" }}>
          This is an educational demonstration of text classification, calibration and honest evaluation. Don&apos;t rely on it for
          budgeting, taxes or accounting.
        </p>
      </Block>
    </SectionFrame>
  );
}
