"use client";

import { useState } from "react";

import { Block, SectionFrame } from "@/components/explore/SectionFrame";
import { Loaded, useApi } from "@/components/explore/sections/shared";
import { Notice } from "@/components/ui/States";
import { apiUrl, ApiError, fetchApi } from "@/lib/api";
import { int, pct } from "@/lib/format";
import { type BatchResult, batchUrl, type BriefRow, type Examples, MAX_BATCH, money, parseLine } from "@/lib/transactions";

import type { TxSectionProps } from "../TransactionsExplorer";

const DEFAULT_LINES = [
  "SQ *HARBOR POKE BAR, -18.40",
  "PURCHASE AUTHORIZED ON 03/14 CHEVRON 0204411 RENO NV, -52.10",
  "SPOTIFY USA, -11.99",
  "ZELLE FROM TAYLOR M, 60",
  "CITY OF DENVER UTILITIES, -84.20",
  "SUNNY VALLEY URGENT CARE",
].join("\n");

export function SamplesSection({ tryIt }: TxSectionProps) {
  const state = useApi<Examples>(apiUrl("transactions/examples"));
  return (
    <Loaded state={state} title="Samples & batch">
      {(d, stale) => {
        const right = d.samples.filter((s) => s.correct).length;
        return (
          <SectionFrame
            title="Samples & batch"
            stale={stale}
            method="transactions-data"
            methodLabel="Synthetic data"
            answer={
              <>
                On these {d.samples.length} randomly drawn test transactions, from merchants the model never saw in training, it gets{" "}
                {right} right. Every row is synthetic: generated by code, not taken from anyone&apos;s statement.
              </>
            }
          >
            <Block
              title="Held-out test transactions"
              caption="A fixed random sample of the test split, predicted live by the engine. Wrong rows are usually brands the model never saw, where the name itself carries no category words. Select a description to see why the model chose what it did."
            >
              <div className="table-wrap" tabIndex={0}>
                <table className="table">
                  <caption className="visually-hidden">Sample test transactions with true and predicted categories</caption>
                  <thead>
                    <tr>
                      <th scope="col">Description</th>
                      <th scope="col">Amount</th>
                      <th scope="col" className="left">
                        Actual
                      </th>
                      <th scope="col" className="left">
                        Predicted
                      </th>
                      <th scope="col">Probability</th>
                      <th scope="col" className="left">
                        Result
                      </th>
                    </tr>
                  </thead>
                  <tbody>
                    {d.samples.map((s, i) => (
                      <tr key={i}>
                        <td className="tx-desc-cell">
                          <button type="button" className="tx-link" onClick={() => tryIt({ d: s.description, a: s.amount })}>
                            {s.description}
                          </button>
                        </td>
                        <td>{money(s.amount)}</td>
                        <td className="left">{s.label}</td>
                        <td className="left">{s.prediction?.label}</td>
                        <td>{s.prediction ? pct(s.prediction.probability, 0) : "n/a"}</td>
                        <td className={"left " + (s.correct ? "" : "neg")}>{s.correct ? "Right" : "Wrong"}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </Block>
            <BatchBlock onTry={tryIt} />
          </SectionFrame>
        );
      }}
    </Loaded>
  );
}

function BatchBlock({ onTry }: { onTry: TxSectionProps["tryIt"] }) {
  const [text, setText] = useState(DEFAULT_LINES);
  const [rows, setRows] = useState<{ d: string; a: number | null; r: BriefRow }[] | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [busy, setBusy] = useState(false);
  const lines = text.split("\n").map(parseLine).filter((x): x is { d: string; a: number | null } => x !== null);
  const tooMany = lines.length > MAX_BATCH;

  const run = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!lines.length || tooMany) return;
    setBusy(true);
    setError(null);
    try {
      const res = await fetchApi<BatchResult>(batchUrl(lines));
      setRows(lines.map((l, i) => ({ ...l, r: res.rows[i] })));
    } catch (err) {
      setError(err instanceof ApiError ? err.message : "The batch could not be categorized.");
    } finally {
      setBusy(false);
    }
  };

  return (
    <Block
      title="Categorize your own list"
      caption={"One transaction per line, with an optional amount after a comma (negative for money out). Up to " + MAX_BATCH + " lines. Nothing is stored: the lines go to the engine in the request and come straight back."}
    >
      <form onSubmit={run} className="tx-batch">
        <label htmlFor="tx-batch-input" className="small muted">
          Transactions, one per line
        </label>
        <textarea
          id="tx-batch-input"
          className="input tx-batch__input"
          rows={7}
          value={text}
          spellCheck={false}
          onChange={(e) => setText(e.target.value)}
          aria-invalid={tooMany || undefined}
        />
        <div style={{ display: "flex", gap: 12, alignItems: "center", flexWrap: "wrap" }}>
          <button type="submit" className="button button--small" disabled={busy || !lines.length || tooMany}>
            {busy ? "Categorizing…" : "Categorize " + int(lines.length) + (lines.length === 1 ? " line" : " lines")}
          </button>
          {tooMany && <span className="xsmall neg">At most {MAX_BATCH} lines at a time.</span>}
        </div>
      </form>
      {error && <Notice tone="error">{error}</Notice>}
      {rows && (
        <div className="table-wrap" tabIndex={0} style={{ marginTop: 16 }}>
          <table className="table">
            <caption className="visually-hidden">Your transactions with predicted categories</caption>
            <thead>
              <tr>
                <th scope="col">Description</th>
                <th scope="col">Amount</th>
                <th scope="col" className="left">
                  Predicted
                </th>
                <th scope="col">Probability</th>
                <th scope="col" className="left">
                  Main reason
                </th>
              </tr>
            </thead>
            <tbody>
              {rows.map((row, i) => (
                <tr key={i}>
                  <td className="tx-desc-cell">
                    {row.r.error ? (
                      row.d
                    ) : (
                      <button type="button" className="tx-link" onClick={() => onTry({ d: row.d, a: row.a })}>
                        {row.d}
                      </button>
                    )}
                  </td>
                  <td>{money(row.a)}</td>
                  {row.r.error ? (
                    <td className="left neg" colSpan={3} style={{ whiteSpace: "normal" }}>
                      {row.r.error}
                    </td>
                  ) : (
                    <>
                      <td className="left">{row.r.prediction?.label}</td>
                      <td>{row.r.prediction ? pct(row.r.prediction.probability, 0) : "n/a"}</td>
                      <td className="left" style={{ fontFamily: "var(--font-mono)" }}>
                        {row.r.why?.[0]?.display ?? "n/a"}
                      </td>
                    </>
                  )}
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
    </Block>
  );
}
